// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.1
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "../ui.h"

void ui_Init_screen_init(void)
{
    ui_Init = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Init, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label7 = lv_label_create(ui_Init);
    lv_obj_set_width(ui_Label7, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label7, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label7, 0);
    lv_obj_set_y(ui_Label7, 26);
    lv_obj_set_align(ui_Label7, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_Label7, "Initialization");

    ui_Container7 = lv_obj_create(ui_Init);
    lv_obj_remove_style_all(ui_Container7);
    lv_obj_set_width(ui_Container7, 199);
    lv_obj_set_height(ui_Container7, 105);
    lv_obj_set_x(ui_Container7, 39);
    lv_obj_set_y(ui_Container7, 68);
    lv_obj_set_flex_flow(ui_Container7, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Container7, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui_Container7, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Container4 = lv_obj_create(ui_Container7);
    lv_obj_remove_style_all(ui_Container4);
    lv_obj_set_width(ui_Container4, 114);
    lv_obj_set_height(ui_Container4, 94);
    lv_obj_set_x(ui_Container4, -40);
    lv_obj_set_y(ui_Container4, -2);
    lv_obj_set_align(ui_Container4, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Container4, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_Container4, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui_Container4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label12 = lv_label_create(ui_Container4);
    lv_obj_set_width(ui_Label12, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label12, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label12, 4);
    lv_obj_set_y(ui_Label12, 4);
    lv_label_set_text(ui_Label12, "IP:");

    ui_Label8 = lv_label_create(ui_Container4);
    lv_obj_set_width(ui_Label8, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label8, LV_SIZE_CONTENT);    /// 1
    lv_label_set_text(ui_Label8, "Verbrauch:");

    ui_Label9 = lv_label_create(ui_Container4);
    lv_obj_set_width(ui_Label9, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label9, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label9, 0);
    lv_obj_set_y(ui_Label9, 16);
    lv_label_set_text(ui_Label9, "Produktion:");

    ui_Label10 = lv_label_create(ui_Container4);
    lv_obj_set_width(ui_Label10, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label10, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label10, 0);
    lv_obj_set_y(ui_Label10, 16);
    lv_label_set_text(ui_Label10, "Netzverbrauch:");

    ui_Container5 = lv_obj_create(ui_Container7);
    lv_obj_remove_style_all(ui_Container5);
    lv_obj_set_width(ui_Container5, 89);
    lv_obj_set_height(ui_Container5, 94);
    lv_obj_set_x(ui_Container5, -40);
    lv_obj_set_y(ui_Container5, -2);
    lv_obj_set_align(ui_Container5, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Container5, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_Container5, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui_Container5, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_IPLabel = lv_label_create(ui_Container5);
    lv_obj_set_width(ui_IPLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_IPLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_IPLabel, 4);
    lv_obj_set_y(ui_IPLabel, 4);
    lv_label_set_text(ui_IPLabel, "-");

    ui_Verbrauch2 = lv_label_create(ui_Container5);
    lv_obj_set_width(ui_Verbrauch2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Verbrauch2, LV_SIZE_CONTENT);    /// 1
    lv_label_set_text(ui_Verbrauch2, "0");

    ui_Produktion2 = lv_label_create(ui_Container5);
    lv_obj_set_width(ui_Produktion2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Produktion2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Produktion2, 0);
    lv_obj_set_y(ui_Produktion2, 16);
    lv_label_set_text(ui_Produktion2, "0");

    ui_Netz2 = lv_label_create(ui_Container5);
    lv_obj_set_width(ui_Netz2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Netz2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Netz2, 0);
    lv_obj_set_y(ui_Netz2, 16);
    lv_label_set_text(ui_Netz2, "0");

}
