// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.1
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "../ui.h"

void ui_OTA_screen_init(void)
{
    ui_OTA = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_OTA, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_FirmwareBar = lv_bar_create(ui_OTA);
    lv_bar_set_value(ui_FirmwareBar, 25, LV_ANIM_OFF);
    lv_bar_set_start_value(ui_FirmwareBar, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_FirmwareBar, 150);
    lv_obj_set_height(ui_FirmwareBar, 10);
    lv_obj_set_align(ui_FirmwareBar, LV_ALIGN_CENTER);

    ui_Label6 = lv_label_create(ui_OTA);
    lv_obj_set_width(ui_Label6, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label6, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label6, 0);
    lv_obj_set_y(ui_Label6, 26);
    lv_obj_set_align(ui_Label6, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_Label6, "Firmware update");

}
