// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.1
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "../ui.h"

void ui_PV_screen_init(void)
{
    ui_PV = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_PV, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_PV, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PV, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TabView1 = lv_tabview_create(ui_PV, LV_DIR_BOTTOM, 50);
    lv_obj_set_width(ui_TabView1, 481);
    lv_obj_set_height(ui_TabView1, 480);
    lv_obj_set_align(ui_TabView1, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_TabView1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags


    ui_TabPage1 = lv_tabview_add_tab(ui_TabView1, "PV");

    ui_PreisLabel = lv_label_create(ui_TabPage1);
    lv_obj_set_width(ui_PreisLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_PreisLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_PreisLabel, 4);
    lv_obj_set_y(ui_PreisLabel, 4);
    lv_label_set_text(ui_PreisLabel, "Strompreis:");
    lv_obj_set_style_text_color(ui_PreisLabel, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_PreisLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Batterie = lv_bar_create(ui_TabPage1);
    lv_bar_set_range(ui_Batterie, 5, 95);
    lv_bar_set_start_value(ui_Batterie, 5, LV_ANIM_OFF);
    lv_obj_set_width(ui_Batterie, 24);
    lv_obj_set_height(ui_Batterie, 198);
    lv_obj_set_x(ui_Batterie, 327);
    lv_obj_set_y(ui_Batterie, 34);
    lv_obj_set_style_bg_color(ui_Batterie, lv_color_hex(0x00FF00), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Batterie, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Preis = lv_label_create(ui_TabPage1);
    lv_obj_set_width(ui_Preis, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Preis, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Preis, 17);
    lv_obj_set_y(ui_Preis, 28);
    lv_label_set_text(ui_Preis, "-");
    lv_obj_set_style_text_color(ui_Preis, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Preis, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PVRing = lv_btn_create(ui_TabPage1);
    lv_obj_set_width(ui_PVRing, 80);
    lv_obj_set_height(ui_PVRing, 80);
    lv_obj_set_x(ui_PVRing, 135);
    lv_obj_set_y(ui_PVRing, 10);
    lv_obj_add_flag(ui_PVRing, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_PVRing, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_PVRing, 50, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_PVRing, lv_color_hex(0x0F2FE9), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PVRing, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_PVRing, &ui_img_pv_png, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_PVRing, lv_color_hex(0x00FF00), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_PVRing, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_PVRing, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_PVRing, lv_color_hex(0xFFFF00), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_PVRing, 100, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_PVRing, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_PVRing, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_PVRing, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_PVRing, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_PVRing, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_PVRing, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_PVRing, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PV1 = lv_label_create(ui_PVRing);
    lv_obj_set_width(ui_PV1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_PV1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_PV1, 0);
    lv_obj_set_y(ui_PV1, 20);
    lv_obj_set_align(ui_PV1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_PV1, "-\nW");

    ui_Batteriewert = lv_label_create(ui_TabPage1);
    lv_obj_set_width(ui_Batteriewert, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Batteriewert, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Batteriewert, 255);
    lv_obj_set_y(ui_Batteriewert, 104);
    lv_label_set_text(ui_Batteriewert, "-");

    ui_Hausring = lv_btn_create(ui_TabPage1);
    lv_obj_set_width(ui_Hausring, 80);
    lv_obj_set_height(ui_Hausring, 80);
    lv_obj_set_x(ui_Hausring, 135);
    lv_obj_set_y(ui_Hausring, 160);
    lv_obj_add_flag(ui_Hausring, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Hausring, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Hausring, 50, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Hausring, lv_color_hex(0x0F2FE9), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Hausring, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_Hausring, &ui_img_haus_png, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Hausring, lv_color_hex(0x00FF00), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Hausring, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Hausring, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_Hausring, lv_color_hex(0xFFFF00), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_Hausring, 100, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_Hausring, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_Hausring, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_Hausring, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Hausring, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Hausring, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Hausring, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_Hausring, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Verbrauch1 = lv_label_create(ui_Hausring);
    lv_obj_set_width(ui_Verbrauch1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Verbrauch1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Verbrauch1, 0);
    lv_obj_set_y(ui_Verbrauch1, 20);
    lv_obj_set_align(ui_Verbrauch1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Verbrauch1, "-\nW");

    ui_NetzRing = lv_btn_create(ui_TabPage1);
    lv_obj_set_width(ui_NetzRing, 80);
    lv_obj_set_height(ui_NetzRing, 80);
    lv_obj_set_x(ui_NetzRing, 40);
    lv_obj_set_y(ui_NetzRing, 85);
    lv_obj_add_flag(ui_NetzRing, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_NetzRing, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_NetzRing, 50, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_NetzRing, lv_color_hex(0x0F2FE9), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_NetzRing, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_NetzRing, &ui_img_netz_png, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_NetzRing, lv_color_hex(0x00FF00), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_NetzRing, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_NetzRing, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_NetzRing, lv_color_hex(0xFFFF00), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_NetzRing, 100, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_NetzRing, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_NetzRing, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_NetzRing, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_NetzRing, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_NetzRing, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_NetzRing, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_NetzRing, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Netz1 = lv_label_create(ui_NetzRing);
    lv_obj_set_width(ui_Netz1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Netz1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Netz1, 0);
    lv_obj_set_y(ui_Netz1, 20);
    lv_obj_set_align(ui_Netz1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Netz1, "-\nW");

    ui_AkkuRing = lv_btn_create(ui_TabPage1);
    lv_obj_set_width(ui_AkkuRing, 80);
    lv_obj_set_height(ui_AkkuRing, 80);
    lv_obj_set_x(ui_AkkuRing, 230);
    lv_obj_set_y(ui_AkkuRing, 85);
    lv_obj_add_flag(ui_AkkuRing, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_AkkuRing, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_AkkuRing, 50, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_AkkuRing, lv_color_hex(0x0F2FE9), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_AkkuRing, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_AkkuRing, &ui_img_akku_png, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_AkkuRing, lv_color_hex(0x00FF00), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_AkkuRing, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_AkkuRing, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_AkkuRing, lv_color_hex(0xFFFF00), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_AkkuRing, 100, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_AkkuRing, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_AkkuRing, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_AkkuRing, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_AkkuRing, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_AkkuRing, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_AkkuRing, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_AkkuRing, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Akku1 = lv_label_create(ui_AkkuRing);
    lv_obj_set_width(ui_Akku1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Akku1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Akku1, 0);
    lv_obj_set_y(ui_Akku1, 20);
    lv_obj_set_align(ui_Akku1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Akku1, "-\nW");

    ui_Lichtseite = lv_tabview_add_tab(ui_TabView1, "Licht");

    ui_SofaLicht = lv_obj_create(ui_Lichtseite);
    lv_obj_remove_style_all(ui_SofaLicht);
    lv_obj_set_width(ui_SofaLicht, 100);
    lv_obj_set_height(ui_SofaLicht, 389);
    lv_obj_set_x(ui_SofaLicht, 154);
    lv_obj_set_y(ui_SofaLicht, 0);
    lv_obj_set_align(ui_SofaLicht, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_SofaLicht, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_SofaLicht, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_SofaLicht, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_SofaToggle = lv_switch_create(ui_SofaLicht);
    lv_obj_set_width(ui_SofaToggle, 50);
    lv_obj_set_height(ui_SofaToggle, 25);
    lv_obj_set_x(ui_SofaToggle, 105);
    lv_obj_set_y(ui_SofaToggle, -186);
    lv_obj_set_align(ui_SofaToggle, LV_ALIGN_TOP_RIGHT);
    lv_obj_set_style_pad_left(ui_SofaToggle, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_SofaToggle, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_SofaToggle, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_SofaToggle, 0, LV_PART_MAIN | LV_STATE_DEFAULT);


    ui_Label1 = lv_label_create(ui_SofaLicht);
    lv_obj_set_width(ui_Label1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label1, "Sofa");
    lv_obj_set_style_pad_left(ui_Label1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Label1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Label1, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Label1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SofaSlider = lv_slider_create(ui_SofaLicht);
    lv_slider_set_value(ui_SofaSlider, 50, LV_ANIM_OFF);
    if(lv_slider_get_mode(ui_SofaSlider) == LV_SLIDER_MODE_RANGE) lv_slider_set_left_value(ui_SofaSlider, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_SofaSlider, 67);
    lv_obj_set_flex_grow(ui_SofaSlider, 1);
    lv_obj_set_x(ui_SofaSlider, 157);
    lv_obj_set_y(ui_SofaSlider, 31);
    lv_obj_set_align(ui_SofaSlider, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_SofaSlider, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SofaSlider, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_SofaSlider, &ui_img_pot_ver_line_png, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_SofaSlider, 28, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_SofaSlider, 28, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_SofaSlider, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_SofaSlider, 12, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_SofaSlider, lv_color_hex(0xF0FF50), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SofaSlider, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_SofaSlider, lv_color_hex(0xF0FF50), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_SofaSlider, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_SofaSlider, 50, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_SofaSlider, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_blend_mode(ui_SofaSlider, LV_BLEND_MODE_NORMAL, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_radius(ui_SofaSlider, 12, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_SofaSlider, lv_color_hex(0x50FF7D), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SofaSlider, 0, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_main_stop(ui_SofaSlider, 0, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_stop(ui_SofaSlider, 255, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_SofaSlider, &ui_img_pot_ver_knob_png, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_SofaSlider, lv_color_hex(0x000000), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_SofaSlider, 255, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_SofaSlider, 30, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_SofaSlider, 0, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_ofs_x(ui_SofaSlider, 5, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_ofs_y(ui_SofaSlider, 5, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_SofaSlider, 3, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_SofaSlider, 2, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_SofaSlider, 6, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_SofaSlider, 6, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_TischLicht1 = lv_obj_create(ui_Lichtseite);
    lv_obj_remove_style_all(ui_TischLicht1);
    lv_obj_set_width(ui_TischLicht1, 100);
    lv_obj_set_height(ui_TischLicht1, 389);
    lv_obj_set_x(ui_TischLicht1, 17);
    lv_obj_set_y(ui_TischLicht1, 0);
    lv_obj_set_align(ui_TischLicht1, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_TischLicht1, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_TischLicht1, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_TischLicht1, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_TischToggle = lv_switch_create(ui_TischLicht1);
    lv_obj_set_width(ui_TischToggle, 50);
    lv_obj_set_height(ui_TischToggle, 25);
    lv_obj_set_x(ui_TischToggle, 105);
    lv_obj_set_y(ui_TischToggle, -186);
    lv_obj_set_align(ui_TischToggle, LV_ALIGN_TOP_RIGHT);


    ui_Label2 = lv_label_create(ui_TischLicht1);
    lv_obj_set_width(ui_Label2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label2, "Esstisch");
    lv_obj_set_style_pad_left(ui_Label2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Label2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Label2, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Label2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Tischslider = lv_slider_create(ui_TischLicht1);
    lv_slider_set_value(ui_Tischslider, 50, LV_ANIM_OFF);
    if(lv_slider_get_mode(ui_Tischslider) == LV_SLIDER_MODE_RANGE) lv_slider_set_left_value(ui_Tischslider, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_Tischslider, 67);
    lv_obj_set_flex_grow(ui_Tischslider, 1);
    lv_obj_set_x(ui_Tischslider, 157);
    lv_obj_set_y(ui_Tischslider, 31);
    lv_obj_set_align(ui_Tischslider, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_Tischslider, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Tischslider, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_Tischslider, &ui_img_pot_ver_line_png, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_Tischslider, 28, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Tischslider, 28, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Tischslider, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Tischslider, 12, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_Tischslider, lv_color_hex(0xF0FF50), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Tischslider, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_Tischslider, lv_color_hex(0xF0FF50), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_Tischslider, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_Tischslider, 50, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_Tischslider, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_blend_mode(ui_Tischslider, LV_BLEND_MODE_NORMAL, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_radius(ui_Tischslider, 12, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Tischslider, lv_color_hex(0x50FF7D), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Tischslider, 0, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_main_stop(ui_Tischslider, 0, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_stop(ui_Tischslider, 255, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_Tischslider, &ui_img_pot_ver_knob_png, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_Tischslider, lv_color_hex(0x000000), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_Tischslider, 255, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_Tischslider, 30, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_Tischslider, 0, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_ofs_x(ui_Tischslider, 5, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_ofs_y(ui_Tischslider, 5, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_Tischslider, 3, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Tischslider, 2, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Tischslider, 6, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Tischslider, 6, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_TabPage3 = lv_tabview_add_tab(ui_TabView1, "PV_STAT");

    ui_PVChart2 = lv_chart_create(ui_TabPage3);
    lv_obj_set_width(ui_PVChart2, 400);
    lv_obj_set_height(ui_PVChart2, 300);
    lv_obj_set_x(ui_PVChart2, 5);
    lv_obj_set_y(ui_PVChart2, -8);
    lv_obj_set_align(ui_PVChart2, LV_ALIGN_CENTER);
    lv_chart_set_type(ui_PVChart2, LV_CHART_TYPE_LINE);
    lv_chart_set_axis_tick(ui_PVChart2, LV_CHART_AXIS_PRIMARY_X, 10, 5, 5, 2, true, 50);
    lv_chart_set_axis_tick(ui_PVChart2, LV_CHART_AXIS_PRIMARY_Y, 10, 5, 5, 2, true, 50);
    lv_chart_set_axis_tick(ui_PVChart2, LV_CHART_AXIS_SECONDARY_Y, 10, 5, 5, 2, true, 25);
    lv_chart_series_t * ui_PVChart2_series_1 = lv_chart_add_series(ui_PVChart2, lv_color_hex(0xE2FF00),
                                                                   LV_CHART_AXIS_PRIMARY_Y);
    static lv_coord_t ui_PVChart2_series_1_array[] = { 0, 10, 20, 40, 80, 80, 40, 20, 10, 0 };
    lv_chart_set_ext_y_array(ui_PVChart2, ui_PVChart2_series_1, ui_PVChart2_series_1_array);




}
