// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.1
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "../ui.h"


// COMPONENT Batteriewert

lv_obj_t * ui_Batteriewert_create(lv_obj_t * comp_parent)
{

    lv_obj_t * cui_Batteriewert;
    cui_Batteriewert = lv_label_create(comp_parent);
    lv_obj_set_width(cui_Batteriewert, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(cui_Batteriewert, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(cui_Batteriewert, 161);
    lv_obj_set_y(cui_Batteriewert, 195);
    lv_label_set_text(cui_Batteriewert, "Batterie:");

    lv_obj_t ** children = lv_mem_alloc(sizeof(lv_obj_t *) * _UI_COMP_BATTERIEWERT_NUM);
    children[UI_COMP_BATTERIEWERT_BATTERIEWERT] = cui_Batteriewert;
    lv_obj_add_event_cb(cui_Batteriewert, get_component_child_event_cb, LV_EVENT_GET_COMP_CHILD, children);
    lv_obj_add_event_cb(cui_Batteriewert, del_component_child_event_cb, LV_EVENT_DELETE, children);
    ui_comp_Batteriewert_create_hook(cui_Batteriewert);
    return cui_Batteriewert;
}

