// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.1
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"
#include "ui_helpers.h"

///////////////////// VARIABLES ////////////////////


// SCREEN: ui_PV
void ui_PV_screen_init(void);
lv_obj_t * ui_PV;
lv_obj_t * ui_TabView1;
lv_obj_t * ui_TabPage1;
lv_obj_t * ui_PreisLabel;
lv_obj_t * ui_Batterie;
lv_obj_t * ui_Preis;
lv_obj_t * ui_PVRing;
lv_obj_t * ui_PV1;
lv_obj_t * ui_Batteriewert;
lv_obj_t * ui_Hausring;
lv_obj_t * ui_Verbrauch1;
lv_obj_t * ui_NetzRing;
lv_obj_t * ui_Netz1;
lv_obj_t * ui_AkkuRing;
lv_obj_t * ui_Akku1;
lv_obj_t * ui_Lichtseite;
lv_obj_t * ui_SofaLicht;
lv_obj_t * ui_SofaToggle;
lv_obj_t * ui_Label1;
lv_obj_t * ui_SofaSlider;
lv_obj_t * ui_TischLicht1;
lv_obj_t * ui_TischToggle;
lv_obj_t * ui_Label2;
lv_obj_t * ui_Tischslider;
lv_obj_t * ui_TabPage3;
lv_obj_t * ui_PVChart2;


// SCREEN: ui_OTA
void ui_OTA_screen_init(void);
lv_obj_t * ui_OTA;
lv_obj_t * ui_FirmwareBar;
lv_obj_t * ui_Label6;


// SCREEN: ui_Init
void ui_Init_screen_init(void);
lv_obj_t * ui_Init;
lv_obj_t * ui_Label7;
lv_obj_t * ui_Container7;
lv_obj_t * ui_Container4;
lv_obj_t * ui_Label12;
lv_obj_t * ui_Label8;
lv_obj_t * ui_Label9;
lv_obj_t * ui_Label10;
lv_obj_t * ui_Container5;
lv_obj_t * ui_IPLabel;
lv_obj_t * ui_Verbrauch2;
lv_obj_t * ui_Produktion2;
lv_obj_t * ui_Netz2;
lv_obj_t * ui____initial_actions0;

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
    #error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif
#if LV_COLOR_16_SWAP !=0
    #error "LV_COLOR_16_SWAP should be 0 to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////

///////////////////// FUNCTIONS ////////////////////

///////////////////// SCREENS ////////////////////

void ui_init(void)
{
    LV_EVENT_GET_COMP_CHILD = lv_event_register_id();

    lv_disp_t * dispp = lv_disp_get_default();
    lv_theme_t * theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED),
                                               true, LV_FONT_DEFAULT);
    lv_disp_set_theme(dispp, theme);
    ui_PV_screen_init();
    ui_OTA_screen_init();
    ui_Init_screen_init();
    ui____initial_actions0 = lv_obj_create(NULL);
    lv_disp_load_scr(ui_PV);
}
